spring:
  application:
    name: ndlCommerce
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: ecommerce
  flyway:
    enabled: false
    validate-on-migrate: true
  sendgrid:
    api-key: ${SENDGRID_TOKEN}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
logging:
  pattern:
      console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  level:
    root: warn
management:
  endpoints:
    web:
      exposure:
        include: health,info
api:
  security:
    token:
      secret: ${TOKEN_SECRET}
  versao: 1.0.0
app:
  domain: ${DOMINIO_APLICACAO}
springdoc:
  override-with-generic-response: false